# ---------- rlvr_config_ds_lora.yaml ----------
# ① 继承 DeepSpeed 预设
defaults:
  - ../config/deepspeed_zero@_here_
  - ../config/deepspeed_zero2@_here_
  - ../config/deepspeed_zero3@_here_
  - ../config/deepspeed_zero3_cpuoffload@_here_

hydra:
  run:
    dir: .
  output_subdir: null

# ========= 基础信息 =========
exp_name: "qwen3-1-7B-rlvr-exact-h800-8gpu"
seed: 42
logging_dir: /project/hdtaccuracy/trains/gspo/qwen3_1_7b_choice_v4/logs
output_dir: /project/hdtaccuracy/trains/gspo/qwen3_1_7b_choice_v4/output
num_gpus_per_node: 8      # 8×H800
# num_gpus_per_node: 4      # 2×H800

track_with: wandb
tracker_kwargs:
 api_key: dce12064d30900b2cc538f73e82997de5aafbb96
 project: roll_peralign
 notes: roll_peralign
 tags:
   - rlvr
   - baseline
  

# ========= 训练控制 =========
max_steps: 400
save_steps: 50
logging_steps: 1
# eval_steps: 50
resume_from_checkpoint: false

# ========= RL 超参 =========
rollout_batch_size: 64
prompt_length: 1024
response_length: 2048
importance_sampling: seq
num_return_sequences_in_group: 8
ppo_epochs: 1
adv_estimator: "grpo"
value_clip: 0.5
reward_clip: 10
dual_clip_loss: true
reward_normalize: true
advantage_clip: 2.0
whiten_advantages: true


use_kl_loss: true
kl_loss_coef: 0.001
loss_agg_mode: "seq-mean-token-mean"

# ========= 预训练权重 =========
pretrain: /project/hdtaccuracy/models/base/Qwen3-1.7B
# reward_pretrain: /project/hdtaccuracy/models/base/Qwen3-8B            # critic 初始权重
validation:
  data_args:
    template: qwen3
    file_name:
      - /project/hdtaccuracy/Personality-Alignment/choice_ver/v10/train_data_with_thinking/roll/val.json
    max_samples: 100
  generating_args:
    do_sample: True
    temperature: 0.3
    top_p: 0.7
    top_k: 20
    max_new_tokens: 2048
    num_beams: 1
    num_return_sequences: 1
  
# ========= Actor（训练） =========
actor_train:
  model_args:
    dtype: bf16
    flash_attn: fa2
    attn_implementation: fa2
    disable_gradient_checkpointing: false
    # —— LoRA 超参 ——                                   # 可按需微调
    # lora_rank: 8
    # lora_target: q_proj,k_proj,v_proj,o_proj
    # lora_alpha: 32
    # lora_dropout: 0.05
  training_args:
    learning_rate: 1.0e-6    # LoRA 常用 1e-4–1e-3
    weight_decay: 0.0
    per_device_train_batch_size: 16   # ZeRO-3 显存足够可翻倍
    gradient_accumulation_steps: 16  # 2×16 ≈ 原来 1×32
    warmup_steps: 0
    num_train_epochs: 5
    max_samples: 9000
  data_args:
    template: qwen3
    file_name:
      - /project/hdtaccuracy/Personality-Alignment/choice_ver/v10/train_data_with_thinking/roll/train.json
    dataset_dir: /project/hdtaccuracy/Personality-Alignment/choice_ver/v10/train_data_with_thinking/roll/
    messages: messages
    domain_interleave_probs:
      # llm_judge: 1.0
      math_rule: 1.0
  # strategy_args:
    # strategy_name: deepspeed_train         # ← 从 megatron_train 改成 DS
    # strategy_config: 
    #   train_micro_batch_size_per_gpu: auto
    #   bf16:
    #     enabled: true
    #   fp16:
    #     enabled: false
    #   zero_optimization:
    #     stage: 3
    #     overlap_comm: true
    #     contiguous_gradients: true
    #     reduce_scatter: true
    #     allgather_partitions: true
    #     allgather_bucket_size: 500000000    # 5e8
    #     reduce_bucket_size: 500000000    # 5e8

    #     stage3_prefetch_bucket_size: 500000000
    #     stage3_param_persistence_threshold: 1000000
    #     stage3_gather_16bit_weights_on_model_save: true
  strategy_args:
    strategy_name: megatron_train
    strategy_config:
      sequence_parallel: true
      tensor_model_parallel_size: 2
      context_parallel_size: 2
      # expert_model_parallel_size: 1
      pipeline_model_parallel_size: 1
      overlap_grad_reduce: true
      use_distributed_optimizer: true
      bf16: true

  device_mapping: "[0, 1, 2, 3, 4 ,5, 6, 7]"             # 与原先保持一致
  # device_mapping: "[0, 1]"
  # infer_batch_size: 8

# ========= Actor（推理/采样） =========
actor_infer:
  model_args:
    dtype: bf16
    flash_attn: fa2
    attn_implementation: fa2
    # lora_rank: 8
    # lora_alpha: 32
    # lora_dropout: 0.05
    # lora_target: q_proj,k_proj,v_proj,o_proj
  generating_args:
    max_new_tokens: 2048
    do_sample: false
    num_beams: 1
    num_return_sequences: ${num_return_sequences_in_group}
  data_args:
    template: qwen3
  strategy_args:
    strategy_name: vllm
    strategy_config:
      gpu_memory_utilization: 0.4
      block_size: 16
      max_model_len: 3072
  num_gpus_per_worker: 1
  device_mapping: "[6,7]"                     # GPU4
  # device_mapping: "[0, 1]"
  infer_batch_size: 2

# ========= Reference =========
reference:
  model_args:
    flash_attn: fa2
    attn_implementation: fa2
    dtype: bf16
  data_args:
    template: qwen3_nothink
  strategy_args:
    strategy_name: megatron_infer
    strategy_config:
      tensor_model_parallel_size: 1
      pipeline_model_parallel_size: 1
  # device_mapping: "[6, 7]"                    # GPU5
  device_mapping: "[0, 1]"
  infer_batch_size: 2

# ========= Reward =========
rewards:
  # vl pipeline support MathRuleRewardWorker only, at present.
  # Support for rewards in other domains will be retained for future implementation.
  math_rule:
    worker_cls: roll.pipeline.rlvr.rewards.math_rule_reward_worker.MathRuleRewardWorker
    model_args:
      model_name_or_path: ${pretrain}
    data_args:
      template: qwen2-vl
    strategy_args:
      strategy_name: hf_infer
      strategy_config: ~
    world_size: 8
    infer_batch_size: 32