python build_choice_training_data.py \
    --questions /project/hdtaccuracy/Personality-Alignment/choice_ver/four_choices_question_v7_hard/all_questions.json \
    --prompts /project/hdtaccuracy/Personality-Alignment/choice_ver/raw_choice_data_v7_hard.jsonl \
    --out /project/hdtaccuracy/Personality-Alignment/choice_ver/four_choices_question_v7_hard_final/v7_hard.json \
    --split_mode user_partial \
    --user_subset_ratio 0.4 \
    --test_ratio 0.4 \
    --make_val \
    --val_ratio 0.25 \
    --show_token_stats \
    --show_stats \
    --tokenizer_model "/project/hdtaccuracy/models/base/Qwen3-4B" \
    --skip_missing_prompt